# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"



default_platform :ios

before_all do
  ensure_git_status_clean
end

platform :ios do
    desc "My awesome app"

    lane :beta do |options|
      changelog = changelog_from_git_commits(
        commits_count: 20, 
        pretty: "- %s",
        date_format: "short",
        match_lightweight_tag: false,
        merge_commit_filtering: "exclude_merges"
      )

      increment_version_number(bump_type: options[:bump_type])
      commit_version_bump(message: "Release v#{get_version_number} :rocket:")
      push_to_git_remote(
        remote: "origin",
        tags: false,
        no_verify: true
      )       
      build
      github_release
      upload_to_testflight(skip_submission: true);
      firebase_app_distribution(
        app: ENV['APP_ID'],
        testers: "swdevicelab@gmail.com",
        release_notes: changelog,
        firebase_cli_path: "/usr/local/bin/firebase"
      )
    end

     lane :build do
      version = get_version_number
        build_ios_app(
          output_directory: "builds/v#{version}",
          export_options: { method: "development" }
        )
    end

    lane :github_release do
      version = get_version_number

      changelog = changelog_from_git_commits(
        commits_count: 20, 
        pretty: "- %s",
        date_format: "short",
        match_lightweight_tag: false,
        merge_commit_filtering: "exclude_merges"
      )

      set_github_release(
        repository_name: "andykitt/gratitude_app",
        api_token: ENV['GITHUB_TOKEN'],
        name: "#{version}",
        tag_name: "v#{version}",
        description: (changelog rescue "No changelog provided"),
        commitish: "master",
        is_prerelease: true,
        upload_assets: ["builds/v#{version}/Runner.ipa"]
      )
    end
end


