# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
    desc "My awesome app"
    lane :envs do
      puts "GITHUB_TOKEN: #{ENV['GITHUB_TOKEN']}"   
    end
    lane :github_release do
      set_github_release(
      repository_name: "andykitt/gratitude_app",
      api_token: ENV["GITHUB_TOKEN"],
      name: "Gratitude App v1.0.1",
      tag_name: "v1.0.1",
      description: (File.read("changelog") rescue "No changelog provided"),
      commitish: "master",
      is_prerelease: true,
      upload_assets: ["builds/Runner.ipa"]
      )
    end
    

    lane :beta do
    increment_version_number(
      bump_type: "patch"
    )
    get_certificates(
      force: false,
    )
    get_provisioning_profile(
      readonly: true,
      development: true
    )
    build_ios_app(
      export_options: {
        method: "development"
      }
    )
    firebase_app_distribution(
      app: "1:775676734756:ios:e6cd7fc053d99dec4d17b1",
      testers: "swdevicelab@gmail.com",
      release_notes: "Lots of amazing new features to test out!",
      firebase_cli_path: "/usr/local/bin/firebase"
    )
    end
     lane :build do
     get_provisioning_profile(
      readonly: true,
      development: true
    )
    build_ios_app(
      export_options: {
        method: "development"
      }
    )

    end
end


